### ISSUE TITLE
Missing options in glauth settings tab

### ISSUE THREAD

**Issue by dl1ch** [sonicnkt/glauth-ui#12]
The Glauth settings tab is missing two values (nameformat and groupformat) under the "backend" section:

[backend]
  datastore = "config"
  baseDN = "dc=glauth,dc=com"
  nameformat = "uid"
  groupformat = "cn"

Please add those two options to the Glauth settings page.

Thanks!

**Comment by sonicnkt** [comment]
I plan to test and merge some other stuff by @traverseda tomorrow and will add this afterwards. Itts easily implemented and i only havent added those options since i didnt need them until now :)

**Comment by sonicnkt** [comment]
So with my last commit i added the missing backend options to the app (nameformat, groupformat and sshkeyattr). If you are not running this using docker you have to migrate your current db with the migrations script (flask db upgrade) otherwise this should be done automatically.
